[Keystone] add rate-limit middleware
sapcc/keystone pull request #7
Opened 2020-10-23 05:55 UTC by rajivmucheli

Hi @Carthaca,

Please validate this PR.

Regards,
Rajiv

2020-10-23 12:30 UTC, Carthaca requested changes
Hi, please have a look inline. Also you don't need to specify the configs if you use the default value (max_sleep_time_seconds,log_sleep_time_seconds,backend_port etc.)

2020-10-23 12:30 UTC, Carthaca commented on keystone/server/flask/core.py
> +                ep='rate_limit',
the endpoint must be `rate-limit` see https://github.com/sapcc/openstack-rate-limit-middleware/blob/master/setup.cfg#L33-L39

2020-10-23 12:30 UTC, Carthaca commented on keystone/server/flask/core.py
> +                      'rate_limit_by': 'initiator_project_id',
this is the default - but please also test the results with `initiator_host_address`

2021-06-07 08:31 UTC, rajivmucheli commented
https://github.com/sapcc/keystone/pull/9

2021-06-07 08:31 UTC, closed without merging